name: quintaplaya
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - pandas
  - scipy
  - xarray
  - netcdf4
  - geopandas
  - matplotlib
  - ipykernel
  - laspy
  - rasterio
  - math
  - pip:
    - loess          # Cappellari (2013) loess_1d / loess_2d — pip only
    - bluemath-tk    # Bluemath (2023) bluemath-tk — pip only

